"""Shared helper modules for Command Center scripts."""

from .pathing import slugify_relative
from .artifacts import (
    ReportArtifact,
    WriteReportArtifactsResult,
    copy_latest_artifact,
    write_report_artifacts,
)
from .build_commandview_selector import (
    SelectorRecord,
    build_commandview_selector,
    build_commandview_selector_payload,
    dump_commandview_selector,
)
from .cli import (
    KeepSpec,
    OptionsConfig,
    PathSpec,
    PathsConfig,
    build_keep_counts,
    build_paths,
    build_standard_options,
    build_standard_paths,
    normalize_keep_count,
    resolve_path,
    resolve_repo_root,
)
from .guardrails import (
    GuardrailConfig,
    GuardrailConfigError,
    GuardrailConstraints,
    GuardrailViolationError,
    enforce_report_naming,
    enforce_run_size_limit,
    load_guardrail_config,
)
from .manifest import (
    AutomationManifest,
    GuardrailState,
    ManifestFile,
    build_automation_manifest,
    write_automation_manifest,
)
from .metrics import (
    MetricsSummary,
    TestRunResult,
    build_metrics_summary,
    write_metrics_summary,
)
from .topic_pipeline import (
    SkipTopicStep,
    TopicContext,
    TopicPipeline,
    TopicPipelineResult,
    TopicStep,
    TopicStepOutcome,
    TopicStepReport,
    build_topic_pipeline,
    step_failed,
    step_skipped,
    step_success,
)
from .summarizer_runner import load_summarizer, run_summarizer, SummarizerError
from .telemetry_emitters import (
    ArtifactMetrics,
    TopicTelemetry,
    build_pipeline_telemetry,
    measure_artifact_directory,
)
from .catalog_registry import CatalogEntry, CatalogRegistry
from .prune_logs import PruneResult, prune_run_directories
from .report_paths import (
    AGGREGATOR_REPORTS,
    CONSUMER_REPORTS,
    HEALTHVIEW_ROOT,
    ORCHESTRATOR_REPORTS,
    PRODUCER_REPORTS,
    RAWVIEW,
    REPORTS_ROOT,
    REPO_STUDIOS_ROOT,
    SUMMARIZER_REPORTS,
    VALID_TIER_CLASSES,
    TierClass,
    build_absolute_topic_path,
    build_topic_path,
    get_all_class_roots,
    get_class_root,
    get_default_output_dir,
    infer_class_from_script,
    validate_output_path,
)
from .test_log_analysis import (
    TestHealth,
    TestLogAnalysisResult,
    build_test_log_report,
    render_markdown,
    select_full_log,
    select_junit_artifact,
)

__all__ = [
    "slugify_relative",
    "copy_latest_artifact",
    "ReportArtifact",
    "WriteReportArtifactsResult",
    "write_report_artifacts",
    "SelectorRecord",
    "build_commandview_selector",
    "build_commandview_selector_payload",
    "dump_commandview_selector",
    "PathSpec",
    "KeepSpec",
    "build_paths",
    "build_keep_counts",
    "normalize_keep_count",
    "resolve_path",
    "resolve_repo_root",
    "PathsConfig",
    "OptionsConfig",
    "build_standard_paths",
    "build_standard_options",
    "GuardrailConfig",
    "GuardrailConfigError",
    "GuardrailConstraints",
    "GuardrailViolationError",
    "load_guardrail_config",
    "enforce_run_size_limit",
    "enforce_report_naming",
    "AutomationManifest",
    "GuardrailState",
    "ManifestFile",
    "build_automation_manifest",
    "write_automation_manifest",
    "MetricsSummary",
    "TestRunResult",
    "build_metrics_summary",
    "write_metrics_summary",
    "TopicStepOutcome",
    "TopicStepReport",
    "TopicStep",
    "TopicContext",
    "SkipTopicStep",
    "TopicPipeline",
    "TopicPipelineResult",
    "build_topic_pipeline",
    "step_success",
    "step_skipped",
    "step_failed",
    "SummarizerError",
    "load_summarizer",
    "run_summarizer",
    "TopicTelemetry",
    "build_pipeline_telemetry",
    "ArtifactMetrics",
    "measure_artifact_directory",
    "CatalogEntry",
    "CatalogRegistry",
    "PruneResult",
    "prune_run_directories",
    # report_paths
    "REPO_STUDIOS_ROOT",
    "REPORTS_ROOT",
    "HEALTHVIEW_ROOT",
    "AGGREGATOR_REPORTS",
    "CONSUMER_REPORTS",
    "ORCHESTRATOR_REPORTS",
    "PRODUCER_REPORTS",
    "RAWVIEW",
    "SUMMARIZER_REPORTS",
    "VALID_TIER_CLASSES",
    "TierClass",
    "get_class_root",
    "build_topic_path",
    "build_absolute_topic_path",
    "infer_class_from_script",
    "get_default_output_dir",
    "validate_output_path",
    "get_all_class_roots",
    # test_log_analysis
    "TestHealth",
    "TestLogAnalysisResult",
    "select_junit_artifact",
    "select_full_log",
    "build_test_log_report",
    "render_markdown",
]
