#!/usr/bin/env python3
"""Setup script to create .repo_studios/library/ folder structure.

This script generates the complete library hierarchy with all __init__.py files
and placeholder modules for the AI-guided refactoring pipeline.

Usage:
    python setup_library_structure.py [--repo-root /path/to/repo]
"""

from pathlib import Path
import argparse


LIBRARY_STRUCTURE = {
    "filesystem": {
        "path_operations": [
            "compute_relative_path.py",
            "resolve_absolute_path.py",
        ],
        "directory_management": [
            "ensure_directory.py",
            "create_timestamped_dir.py",
        ],
    },
    "artifact_lifecycle": {
        "versioning": [
            "create_latest_link.py",
            "prune_old_runs.py",
        ],
        "structured_output": [
            "write_json_artifact.py",
            "write_markdown_artifact.py",
            "write_log_artifact.py",
            "write_tsv_artifact.py",
        ],
        "schemas": [
            "base_report_schema.py",
        ],
    },
    "time_handling": {
        "parsing": [
            "parse_iso_timestamp_utc.py",
        ],
        "formatting": [
            "format_run_timestamp.py",
        ],
    },
    "logging_setup": {
        "configuration": [
            "configure_basic_logging.py",
        ],
    },
    "cli_patterns": {
        "common_args": [
            "repo_root_arg.py",
            "output_dir_arg.py",
            "timestamp_arg.py",
            "artifacts_to_keep_arg.py",
        ],
    },
}


INIT_PY_TEMPLATE = '''"""Library module: {module_path}

Part of the Repo Studios composable code library.
See .repo_studios/library/README.md for usage guidelines.
"""

__all__ = []
'''


PLACEHOLDER_MODULE_TEMPLATE = '''"""PLACEHOLDER: {module_name}

This module will contain: {purpose}

Status: Awaiting extraction from duplicate detection pipeline.
Target duplicates: TBD after scan_code_duplicates.py runs.

DO NOT IMPLEMENT YET - Will be auto-generated by refactor_from_report.py
"""

# TODO: Function will be extracted here by automation


def placeholder() -> None:
    """Placeholder function - will be replaced during refactoring."""
    raise NotImplementedError(
        f"{__name__} is a placeholder awaiting duplicate extraction"
    )
'''


def create_init_file(path: Path, module_path: str) -> None:
    """Create __init__.py with appropriate content."""
    content = INIT_PY_TEMPLATE.format(module_path=module_path)
    path.write_text(content, encoding="utf-8")
    print(f"  Created: {path}")


def create_placeholder_module(path: Path, module_name: str, purpose: str) -> None:
    """Create placeholder .py module file."""
    content = PLACEHOLDER_MODULE_TEMPLATE.format(
        module_name=module_name,
        purpose=purpose,
    )
    path.write_text(content, encoding="utf-8")
    print(f"  Created: {path}")


def get_module_purpose(module_name: str) -> str:
    """Infer purpose from module filename."""
    purposes = {
        "compute_relative_path": "Convert absolute paths to repo-relative paths",
        "resolve_absolute_path": "Resolve relative paths to absolute with repo root",
        "ensure_directory": "Create directory with parents if not exists",
        "create_timestamped_dir": "Create run directories with timestamp format",
        "create_latest_link": "Create hardlink or copy for 'latest' artifact versioning",
        "prune_old_runs": "Delete old timestamped run directories keeping N most recent",
        "write_json_artifact": "Write JSON report with consistent formatting",
        "write_markdown_artifact": "Generate markdown reports from data structures",
        "write_log_artifact": "Write key=value log format for parsing",
        "write_tsv_artifact": "Generate TSV table outputs",
        "base_report_schema": "Common report structure (schema_version, generated_utc, summary)",
        "parse_iso_timestamp_utc": "Parse ISO timestamp strings to UTC datetime",
        "format_run_timestamp": "Format datetime to %Y%m%d_%H%M%S slug format",
        "configure_basic_logging": "Setup logging with level and format",
        "repo_root_arg": "Reusable --repo-root argument definition",
        "output_dir_arg": "Reusable --output-dir argument definition",
        "timestamp_arg": "Reusable --timestamp argument definition",
        "artifacts_to_keep_arg": "Reusable --artifacts-to-keep argument definition",
    }
    name = module_name.replace(".py", "")
    return purposes.get(name, "Purpose to be determined")


def build_library_structure(repo_root: Path) -> None:
    """Generate the complete library folder structure."""
    library_root = repo_root / ".repo_studios" / "library"
    
    print(f"\nBuilding library structure at: {library_root}")
    print("=" * 60)
    
    # Create root library directory
    library_root.mkdir(parents=True, exist_ok=True)
    print(f"\nCreated library root: {library_root}")
    
    # Create root __init__.py
    create_init_file(library_root / "__init__.py", ".repo_studios.library")
    
    # Iterate through structure
    for top_level, children in LIBRARY_STRUCTURE.items():
        top_path = library_root / top_level
        top_path.mkdir(parents=True, exist_ok=True)
        print(f"\n[{top_level}/]")
        
        # Create top-level __init__.py
        create_init_file(
            top_path / "__init__.py",
            f".repo_studios.library.{top_level}"
        )
        
        # Create subdirectories
        for subdir, modules in children.items():
            sub_path = top_path / subdir
            sub_path.mkdir(parents=True, exist_ok=True)
            
            # Create subdirectory __init__.py
            create_init_file(
                sub_path / "__init__.py",
                f".repo_studios.library.{top_level}.{subdir}"
            )
            
            # Create placeholder module files
            for module in modules:
                module_path = sub_path / module
                purpose = get_module_purpose(module)
                create_placeholder_module(module_path, module, purpose)
    
    print("\n" + "=" * 60)
    print(f"✅ Library structure created successfully!")
    print(f"\nNext steps:")
    print(f"  1. Review: {library_root / 'README.md'}")
    print(f"  2. Review: {repo_root / '.repo_studios' / 'naming_conventions.md'}")
    print(f"  3. Run: scan_code_duplicates.py (Phase 2)")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Setup .repo_studios/library/ folder structure"
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="Repository root directory (default: current directory)",
    )
    args = parser.parse_args()
    
    repo_root = args.repo_root.resolve()
    
    if not repo_root.exists():
        print(f"❌ Error: Repository root does not exist: {repo_root}")
        return 1
    
    build_library_structure(repo_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
